version: 1.0.{build}
configuration: Automated
platform: Win32
install:
- git submodule update --init --recursive
build:
  project: NephQ2.sln
  verbosity: minimal
test: off
artifacts:
- path: bin\EngineTest32.exe
  name: Engine
- path: bin\baseq2\Game_x86.dll
  name: Game
deploy: off
