version: 1.0.{build}
configuration: Automated
platform: Win32
install:
- git submodule update --init --recursive
build:
  project: NephQ2.sln
  verbosity: minimal
test: off
artifacts:
- path: bin
  name: NephQ2
  type: zip
deploy: off
